name: Build code, run unit test, run SAST, run SCA, run DAST
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - run: npm install

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nodejs-playground
            -Dsonar.projectKey=nodejs-playground
      
  security:
    runs-on: ubuntu-latest
    needs: build
    name: Run the SCA scan on the source code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Synk to check for vulnerabilites
        uses: snyk/actions/node@0.4.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
    
  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run the DAST scan on the web application
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP to check for vulnerabilites
        uses: zaproxy/action-baseline@v0.14.0
        with: 
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://example.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'